### ISSUE TITLE
Documentation for all method types

### ISSUE THREAD

**Issue by DanChaltiel** [mjmartens/stoppingrule#1]
Hi,

Thank you for your very nice package.

I'm trying to understand and reproduce your article "Statistical Rules for Safety Monitoring in Clinical Trials" but I'm facing a bit of a documentation issue.

In the article, you illustrate the stopping rules using, among others, 2 Geller et al. and 2 Chen and Chaloner methods: 

> - a weakly informative Geller et al. method with prior mean E(p) = p0 and ν = 2 (Gw); 
> - a strongly informative Geller et al. method with prior mean p0 and ν = 0.25n, making the number of prior observations 25% of the cohort size (Gs); 
> - two Chen and Chaloner methods (CCl and CCm) with weakly informative priors determined by E(p) = p0, ν = 2 and targeted alternative rates p1’s that a fixed sample, exact binomial test provides 65% and 80% power to detect, respectively; 

However, I couldn't manage to understand how to translate this into code.
Would you be so kind as to share the code you used in the article for these methods? 

Also, I'm wondering, why didn't you use a Wang-Tsiatis test in the article?

Best regards,
Dan Chaltiel

PS: Actually, if you have the time to put it together, I think sharing the whole code that generated your article would be a very useful vignette.

**Comment by mjmartens** [comment]
The syntax for the Gw method is
calc.rule.bin(ns=1:n, p0=p0, alpha=alpha, type="BB", params=c(2*p0,2*(1-p0)))

Others can be computed similarly by using the proper inputs for type and params as required by the stopping rule method. Please read the functions' documentation for further details.

Please note that our paper studied the performance of the O'Brien-Fleming test, which is a member of the Wang-Tsiatis family.
