### ISSUE TITLE
Bug in `table.rule.bin()`

### ISSUE THREAD

**Issue by DanChaltiel** [mjmartens/stoppingrule#2]
Hi,

Thank you again for this very helpful package.

In a binary rule where the numbers of subjects are bound (for practical reasons), applying `table.rule.bin()` sometimes creates a weird output with missing values.

Note that `rule$Rule` has no error and no NA, so this really seems to come from `table.rule.bin()`.

If this kind of input is forbidden, maybe `calc.rule.bin()` should throw the appropriate error, and documentation of `ns` should state it clearly.

Here is a reproducible example:

``` r
library(tidyverse)
library(stoppingrule)
calc.rule.bin(ns=c(5,10,15,20,25,30,36), p0=0.20, alpha=0.1, type="Pocock") %>% 
  table.rule.bin() %>% 
  as_tibble()
#> # A tibble: 9 × 2
#>   `N evaluable` `Reject If N >=`
#>   <chr>         <chr>           
#> 1 5 - 9         4               
#> 2 10 - NA       5               
#> 3 NA - 14       <NA>            
#> 4 15 - 19       7               
#> 5 20 - 24       8               
#> 6 25 - NA       9               
#> 7 NA - 29       <NA>            
#> 8 30 - 35       11              
#> 9 36            12
```

<sup>Created on 2024-08-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

If you point me in the right direction, I'd gladly make a pull request.

**Comment by DanChaltiel** [comment]
In case this was indeed a bug and not a misuse of your package, here's a suggestion for an R function that fixes the bug:

```r
table.rule.bin2 = function(x) {
  rule = x$Rule
  rule = rule[rule[, 2] <= rule[, 1], ]
  rb = unique(rule[,2])
  
  n_eval = sapply(rb, function(i){
    rg = range(rule[,1][rule[,2]==i])
    paste(unique(rg), collapse=" - ")
  }, simplify=FALSE)
  
  val = cbind(unlist(n_eval), rb)
  colnames(val) = c("N evaluable", "Reject If N >=")
  
  return(val)
}

rule1 = calc.rule.bin(ns=1:36, p0=0.20, alpha=0.1, type="Pocock")
x1=table.rule.bin(rule1)
x2=table.rule.bin2(rule1)
identical(x1, x2)
#TRUE

rule2 = calc.rule.bin(ns=c(5,10,15,20,25,30,36), p0=0.20, alpha=0.1, type="Pocock")
x1=table.rule.bin(rule2)
x2=table.rule.bin2(rule2)
identical(x1, x2)
#FALSE

x2
#     N evaluable Reject If N >=
#[1,] "5"         "4"           
#[2,] "10"        "5"           
#[3,] "15"        "7"           
#[4,] "20"        "8"           
#[5,] "25"        "9"           
#[6,] "30"        "11"          
#[7,] "36"        "12"          
```

This function yields the same output in the case of a standard, Readme-like call, and does not have any missing value in the case I presented in this issue.

However, as there are no tests, I cannot make sure the output is consistent with all the calls that can be made with your package.

**Comment by mjmartens** [comment]
Thank you for notifying me of this issue. 

An update of the package is planned to be released to GitHub and CRAN this month. We will include a fix of this bug in the new version.

**Comment by mjmartens** [comment]
A stoppingrule package update has been released to this GitHub repository and CRAN which includes a fix for this bug.
